spring:
  mvc:
    view:
      prefix: /WEB-INF/sources/jsp/
      suffix: .jsp

  datasource:
    # MARIADB
    #driverClassName: org.mariadb.jdbc.Driver
    #url: jdbc:mariadb://localhost:3306/sample_db?characterEncoding=UTF-8&serverTimezone=UTC

    # MYSQL
    # 기본
    # driverClassName: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/sample_db?characterEncoding=UTF-8&serverTimezone=UTC
    # username: root
    # password: root

    # MYSQL
    # log4j, Hikari 응용
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/sample_db?characterEncoding=UTF-8&serverTimezone=UTC

    # Hikari
    hikari.username: root
    hikari.password: root
    hikari.maximum-pool-size: 10
    hikari.connection-test-query: SELECT 1